# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.1"

default_platform :android

platform :android do
  desc "Compile a new build for Android"
  lane :release do |options|
   app_android_key = 'alias_name'
    sh("npm run ionic:release:build")
    sign_apk(
      apk_path: "platforms/android/build/outputs/apk/android-release-unsigned.apk",
      signed_apk_path: "apps/ion2Seed.apk",
      keystore_path: "fastlane/release-cred/android.keystore",
      alias: app_android_key,
    )
    zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")
    sh("npm run screenshots:android")
    supply(
      apk: "apps/ion2Seed.apk"
    )
  end
end