# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.1"

default_platform :android

platform :android do
  desc "Compile a new build for Android"
  lane :release do |options|
   app_android_key = 'alias_name'
    sh("npm run ionic:release:build")
    sign_apk(
      apk_path: "platforms/android/build/outputs/apk/android-release-unsigned.apk",
      signed_apk_path: "apps/tinywallet.apk",
      keystore_path: "fastlane/release-cred/android.keystore",
      alias: app_android_key,
    )
    zipalign(apk_path: "#{lane_context[SharedValues::SIGNED_APK_PATH]}")
    sh("npm run screenshots:android")
    supply(
      apk: "apps/tinywallet.apk"
    )
  end
end

platform :ios do
  desc "Compile a new build for for ad-hoc"
  lane :releaseAdhoc do
    app_name_sanitized = 'Tiny Wallet'
    ios_project_path = "platforms/ios/#{app_name_sanitized}.xcodeproj"
    app_identifier = "com.simpleproductionsinc.tinywallet"

    # Compile the ionic app
    sh("npm run build:prod && ionic build ios --release")
    # Get certificate
    cert
    # Get provisioning profile
    sigh(
      force: false
    )
    # Recreate schemes to ensure a smooth transition from cordova to gym
    recreate_schemes(
      project: ios_project_path
    )
    # Archive app into ipa
    gym(
      scheme: app_name_sanitized,
      project: ios_project_path,
      export_method: 'ad-hoc',
      output_directory: './apps'
    )
    crashlytics(
      api_token: "0de21186b656d5ebed3e4d24fb2a8807806c9bf2",
      build_secret: "30126e94122959fdedb21bfbd84cdd48735a9357076a9a091986a9174880cc8e"
    )
  end
end

platform :ios do
  desc "Compile a new build for for appstore"
  lane :release do
    app_name_sanitized = 'Tiny Wallet'
    ios_project_path = "platforms/ios/#{app_name_sanitized}.xcodeproj"
    app_identifier = "com.simpleproductionsinc.tinywallet"

    # Compile the ionic app
    sh("npm run build:prod && ionic build ios --release")
    # Get certificate
    cert
    # Get provisioning profile
    sigh(
      force: false
    )
    # Recreate schemes to ensure a smooth transition from cordova to gym
    recreate_schemes(
      project: ios_project_path
    )
    # Archive app into ipa
    gym(
      scheme: app_name_sanitized,
      project: ios_project_path,
      export_method: 'app-store',
      output_directory: './apps'
    )
  end
end